apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-one
spec:
  rules:
    - host: "go-one.test.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-one
                port:
                  number: 8080
