name: cicd

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: luongvantrong/go-one:${{ env.SHORT_SHA }}

    outputs:
      commit_id: ${{ env.SHORT_SHA }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip3 install yq
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/go-one/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update values.yaml with comit ${{needs.ci.outputs.commit_id}}"

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd

      - name: Argocd Login
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web  \
            --username admin  \
            --password  ${{ secrets.ARGOCD_PASSWORD }}
         

      - name: Sync argocd
        shell: bash
        run: |
          argocd app sync go-one \
           --server argocd-server.argocd